apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3600        # Exposed service port
      targetPort: 3600  # Must match containerPort above
      protocol: TCP
  type: ClusterIP
