apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: ebs
    app: mongodb
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0dc2cb59fad94effe  # 👈 Existing EBS volume ID
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - ap-south-1b  # 👈 Availability Zone of your EBS volume
